apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-workflows

resources:
  - datacube-product-sync.yaml
  - datacube-delete-product.yaml
  - datacube-stac-index.yaml
  - datacube-bulk-index.yaml
  - datacube-metadata-update.yaml
  - cubedash.yaml
  - daily-indexing-template.yaml
