---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: terria
  namespace: terria
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: maps.staging.piksel.big.go.id

spec:
  ingressClassName: nginx
  rules:
    - host: maps.staging.piksel.big.go.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: terria
                port:
                  number: 80

  tls:
    - hosts:
        - maps.staging.piksel.big.go.id
      secretName: terria
