apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: terria

resources:
  - ../../base/terria
  - ingress.yaml

images:
  - name: 686410905891.dkr.ecr.ap-southeast-3.amazonaws.com/terriamap
    newTag: v20260129-1057
