apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datacube-ows
  namespace: open-datacube
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ows-uncached.staging.piksel.big.go.id
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($http_x_public_host != "") {
        set $target_host $http_x_public_host;
      }
      if ($http_x_public_host = "") {
        set $target_host $host;
      }
      proxy_set_header Host $target_host;
      proxy_set_header X-Forwarded-Host $target_host;
spec:
  rules:
    - host: ows-uncached.staging.piksel.big.go.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: datacube-ows-svc
                port:
                  name: http
  tls:
    - hosts:
        - ows-uncached.staging.piksel.big.go.id
      secretName: ows-ingress-tls-staging
