apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datacube-ows
  namespace: open-datacube
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: ows-uncached.staging.piksel.big.go.id

spec:
  rules:
    - host: ows-uncached.staging.piksel.big.go.id
      http:
        paths:
          - path: /healthz
            pathType: Exact
            backend:
              service:
                name: datacube-ows-svc
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: datacube-ows-svc
                port:
                  name: http
  tls:
    - hosts:
        - ows-uncached.staging.piksel.big.go.id
      secretName: ows-ingress-tls-staging
