apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-datacube

resources:
  - ../../base/datacube-ows
  - ingress.yaml

images:
  - name: 686410905891.dkr.ecr.ap-southeast-3.amazonaws.com/piksel-core
    newTag: ows-v20260126-1705
