apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-datacube

resources:
  - ../../base/datacube-ows

configMapGenerator:
  - name: ows-config
    files:
      - ows_config/
    options:
      disableNameSuffixHash: true # Important: keeps configmap name consistent

images:
  - name: 686410905891.dkr.ecr.ap-southeast-3.amazonaws.com/piksel-core
    newTag: ows-v20251029-072223

patches:
  - path: patches/deployment-patch.yaml
  - path: patches/hpa-patch.yaml

commonLabels:
  environment: staging

commonAnnotations:
  deployed-by: "kustomize"
  config-version: "v1.0"
