apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: explorer-ingress
  namespace: open-datacube
  labels:
    app: explorer
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: explorer.staging.piksel.big.go.id
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - explorer.staging.piksel.big.go.id
      secretName: explorer-ingress-tls
  rules:
    - host: explorer.staging.piksel.big.go.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: explorer-svc
                port:
                  number: 80
